CREATE TABLE BIDAIARIA
(
	NAN						 	VARCHAR2(9) PRIMARY KEY ,
	Datupertsonalak			 	VARCHAR2(20),
	Telefonoa				 	NUMBER(9),
	Nazionalitatea			 	VARCHAR2(20)
);
CREATE TABLE HEGALDIRAKO_PLAZA
(
	Lerrozenbakia			 	NUMBER(10),
	Letra					 	VARCHAR2(20),
	Leihoanpasilloanerdian 		VARCHAR2(20),
	CONSTRAINT PK_HEGALDIRAKO_PLAZA PRIMARY KEY (Lerrozenbakia, Letra)
);
CREATE TABLE ERRESERBA
(
	NAN							 VARCHAR2(9),
	Lerrozenbakia				 NUMBER(10),
	Letra						 VARCHAR2(20),
	CONSTRAINT PK_HEGALDIRAKO_PLAZA PRIMARY KEY (NAN, Lerrozenbakia, Letra),
	CONSTRAINT FK_ERRESERBA_NAN FOREIGN KEY (NAN) REFERENCES BIDAIARIA (NAN) ON DELETE CASCADE,
	CONSTRAINT FK_ERRESERBA_LERRO FOREIGN KEY (Lerrozenbakia) REFERENCES HEGALDIRAKO_PLAZA (Lerrozenbakia) ON DELETE CASCADE,
	CONSTRAINT FK_ERRESERBA_LETRA FOREIGN KEY (Letra) REFERENCES HEGALDIRAKO_PLAZA (Letra) ON DELETE CASCADE
);
