CREATE TABLE PATROIA
{
	NAN					VARCHAR2(9),
	Datupertsonalak		VARCHAR2(20),
	Jaiotzadata			DATE,
	Jaiotzatokia		VARCHAR2(20),
	PRIMARY KEY NAN
}
CREATE TABLE TRAINERA
{
	KodTrainera			NUMBER(10),
	Izena				VARCHAR2(20),
	Kluba				VARCHAR2(20),
	Erositakourtea		NUMBER(4),
	NAN					VARCHAR2(9),	
	PRIMARY KEY KodTrainera,
	CONSTRAINT FK_TRAINERA FOREIGN KEY (NAN) REFERENCES PATROIA ON DELETE CASCADE
}
