CREATE TABLE ESKARIAK
(
NIF VARCHAR2(10),
ARTIKULUA VARCHAR2(20),
FABRI_KODEA NUMBER(3),
PISUA NUMBER(3),
KATEGORIA VARCHAR2(10),
ESKARI_DATA DATE,
ESKATUTAKO_UNIT NUMBER(4),
CONSTRAINT PK_ESKARIAK PRIMARY KEY(NIF, ARTIKULUA,FABRI_KODEA,ESKARI_DATA, PISUA),
CONSTRAINT KATEGORI_TARTEA CHECK (KATEGORIA IN('Primera', 'Segunda', 'Tercera'))
CONSTRAINT FK_ARTIKULU FOREIGN KEY (ARTIKULUA) REFERENCES ARTICULOS (ARTIKULUA) ON DELETE CASCADE,
CONSTRAINT FK_FABRI_KODEA FOREIGN KEY (FABRI_KODEA) REFERENCES ARTICULOS (FABRI_KODEA) ON DELETE CASCADE,
CONSTRAINT FK_PISUA FOREIGN KEY (PISUA) REFERENCES ARTICULOS (PISUA) ON DELETE CASCADE,
CONSTRAINT FK_KATEGORIA FOREIGN KEY (KATEGORIA) REFERENCES ARTICULOS (KATEGORIA) ON DELETE CASCADE,

);
CREATE TABLE SALMENTAK
(
NIF VARCHAR2(10),
ARTIKULUA VARCHAR2(20),
FABRI_KODEA NUMBER(3),
PISUA NUMBER(3),
KATEGORIA VARCHAR2(10),
SALMENTA_DATA DATE,
SALDUTAKO_UNIT NUMBER(4),
CONSTRAINT PK_ESKARIAK PRIMARY KEY(NIF, ARTIKULUA,FABRI_KODEA,ESKARI_DATA, PISUA, KATEGORIA, SALMENTA_DATA),
CONSTRAINT FK_KODE FOREIGN KEY (FABRIKA_KODEA) REFERENCES FABRIKATZAILEA (FABRIKA_KODEA) ON DELETE CASCADE,
CONSTRAINT KATEGORI_TARTEA CHECK (KATEGORIA IN('Primera', 'Segunda', 'Tercera'))
CONSTRAINT FK_ARTIKULU FOREIGN KEY (ARTIKULUA) REFERENCES ARTICULOS (ARTIKULUA) ON DELETE CASCADE,
CONSTRAINT FK_FABRI_KODEA FOREIGN KEY (FABRI_KODEA) REFERENCES ARTICULOS (FABRI_KODEA) ON DELETE CASCADE,
CONSTRAINT FK_PISUA FOREIGN KEY (PISUA) REFERENCES ARTICULOS (PISUA) ON DELETE CASCADE,
CONSTRAINT FK_KATEGORIA FOREIGN KEY (KATEGORIA) REFERENCES ARTICULOS (KATEGORIA) ON DELETE CASCADE,

);
