CREATE TABLE PROVINCIAS
(
CODPROVINCIA NUMBER(2) PRIMARY KEY, 
NOM_PROVINCIA VARCHAR2(15)
);

CREATE TABLE PERSONAS 
(
DNI NUMBER(8) PRIMARY KEY,
NOMBRE VARCHAR2(15),
DIRECCION VARCHAR2(25),
POBLACION VARCHAR2(20),
CODPROVIN NUMBER(2),
CONSTRAINT FK_CODPROVIN FOREIGN KEY (CODPROVIN) REFERENCES PROVINCIAS (CODPROVINCIA) ON DELETE CASCADE
);
INSERT INTO PROVINCIAS VALUES (2,'Bizkaia');
INSERT INTO PROVINCIAS VALUES (1,'Araba');
INSERT INTO PROVINCIAS VALUES (3,'Gipuzkoa');
INSERT INTO PROVINCIAS VALUES (4,'NafarroaBeherea');
INSERT INTO PROVINCIAS VALUES (5,'Nafarroa');
INSERT INTO PROVINCIAS VALUES (6,'Lapurdi');
INSERT INTO PROVINCIAS VALUES (7,'Zuberoa');

INSERT INTO PERSONAS VALUES (12345679, 'aaaa', 'Aaaa kalea', 'Itzubaltzeta', 2);
INSERT INTO PERSONAS VALUES (22345679, 'bbbb', 'bbbb kalea', 'Iruñea', 5);
INSERT INTO PERSONAS VALUES (12345678, 'Antón', 'Aurrezki kutxa kalea', 'Itzubaltzeta', 2);


CREATE TABLE EJEMPL02
(
DNI NUMBER(8) PRIMARY KEY, 
NOMBRE VARCHAR2(15),
USUARIO VARCHAR2(10)
);

INSERT INTO EJEMPL02 VALUES (12345678, 'Antón', 'Antón');
INSERT INTO EJEMPL02 VALUES (12345679, 'Gorka', 'Gorka');
INSERT INTO EJEMPL02 VALUES (12345677, 'Unai', 'Unai');
INSERT INTO EJEMPL02 VALUES (12345676, 'Mario', 'Mario');
INSERT INTO EJEMPL02 VALUES (12345675, 'Arrate', 'Arrate');
INSERT INTO EJEMPL02 VALUES (12345674, 'Asier', 'Asier');
INSERT INTO EJEMPL02 VALUES (12345673, 'Jon Ander', 'Jon Ander');
INSERT INTO EJEMPL02 VALUES (12345672, 'Iker', 'Iker');
INSERT INTO EJEMPL02 VALUES (12345671, 'Alejandro', 'Alejandro');
INSERT INTO EJEMPL02 VALUES (12345670, 'Julen', 'Julen');


